### ISSUE TITLE
时间相差8个小时，怎么解决？

### ISSUE THREAD

**Issue by SQGE** [beginor/docker-gitlab-ce#2]
在镜像之间我已经把时间加进去了，目前系统时间是正确的
root@76126b1c9309:/# date
Mon Apr  9 11:25:39 CST 2018

但是创建项目还有创建用户时间还是少了8个小时，请问有什么方法解决吗

**Comment by SQGE** [comment]
已经解决了    --volume /etc/localtime:/etc/localtime

**Comment by beginor** [comment]
时区问题，很容易解决的
