### ISSUE TITLE
装了之后一直拒绝连接

### ISSUE THREAD

**Issue by Orocker** [beginor/docker-gitlab-ce#4]
centos7 迷你版
装好了之后一直 拒绝连接

安装命令：
```
docker run \
        --detach \
         --hostname localhost \
        --publish 8443:443 \
        --publish 8080:80 \
        --name gitlab \
        --restart always \
        --volume /mnt/sda1/gitlab/etc:/etc/gitlab \
        --volume /mnt/sda1/gitlab/log:/var/log/gitlab \
        --volume /mnt/sda1/gitlab/data:/var/opt/gitlab \
        beginor/gitlab-ce:latest
```

docker ps:

```
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                            PORTS                                                 NAMES
d5d99ce8788e        beginor/gitlab-ce:latest   "/assets/wrapper"        2 minutes ago       Up 2 minutes (health: starting)   22/tcp, 0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp   gitlab

```

**Comment by nimrc** [comment]
检查你的防火墙

**Comment by Orocker** [comment]
嗯，防火墙的锅，解决了 @fyibmsd  3Q

**Comment by Orocker** [comment]
@fyibmsd  为什么我修改密码一直报500错误呢？

**Comment by nimrc** [comment]
看docker log啊 哪里有错改哪里

**Comment by Orocker** [comment]
不是docker的错误，docker没有产生错误日志，这个gitlab系统产生的错误在哪 ？

**Comment by Orocker** [comment]
`Started GET "/users/sign_in" for 192.168.1.178 at 2018-11-19 10:29:57 +0000
Processing by SessionsController#new as HTML
Redirected to http://192.168.1.123/users/password/edit?reset_password_token=Rf1VTHFWfUzixA6suBv_
Filter chain halted as :check_initial_setup rendered or redirected
Completed 302 Found in 17066ms (ActiveRecord: 814.7ms)
Started GET "/users/password/edit?reset_password_token=[FILTERED]" for 192.168.1.178 at 2018-11-19 10:30:15 +0000
Processing by PasswordsController#edit as HTML
  Parameters: {"reset_password_token"=>"[FILTERED]"}
Completed 200 OK in 27270ms (Views: 24658.8ms | ActiveRecord: 63.1ms)
Started GET "/help" for 127.0.0.1 at 2018-11-19 10:30:46 +0000
Processing by HelpController#index as */*
Started GET "/help" for 127.0.0.1 at 2018-11-19 10:32:15 +0000
Processing by HelpController#index as */*
Started GET "/help" for 127.0.0.1 at 2018-11-19 10:33:46 +0000
Processing by HelpController#index as */*
Started GET "/help" for 127.0.0.1 at 2018-11-19 10:35:12 +0000
Processing by HelpController#index as */*
`
这是`/mnt/gitlab/log/gitlab-rails/production.log`
