### ISSUE TITLE
语言选项

### ISSUE THREAD

**Issue by atmoxao** [beginor/docker-gitlab-ce#7]
老哥，你说官方最新版的镜像有中文选项  我安装的最新版没有语言选项

**Comment by beginor** [comment]
有的， 登录之后点击右上角的用户头像， 先选择 `settings`  ， 再在左侧找到 `preferences` ， 在 `localization` 中找 `language` 选项就可以了

**Comment by atmoxao** [comment]
找到了  谢了朋友~
